"""initial schema

Revision ID: 87f4abbdf85f
Revises: 
Create Date: 2026-09-18 22:35:43.415001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87f4abbdf85f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_number',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('phone_number_id', sa.Text(), nullable=False),
    sa.Column('waba_id', sa.Text(), nullable=True),
    sa.Column('display_phone', sa.Text(), nullable=False),
    sa.Column('verified_name', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_business_number_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('wa_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('about', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wa_id')
    )
    op.create_table('fcm_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('android', 'ios')", name='ck_fcm_tokens_platform'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_fcm_tokens_token')
    )
    op.create_table('operator',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('wa_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), server_default=sa.text("'You'"), nullable=False),
    sa.Column('about', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_operator_singleton'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', name='uq_operator_phone'),
    sa.UniqueConstraint('wa_id', name='uq_operator_wa_id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_codes_created_at', 'otp_codes', ['created_at'], unique=False)
    op.create_table('webhook_events',
    sa.Column('event_key', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_key')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contact_wa_id', sa.Text(), nullable=False),
    sa.Column('last_message_id', sa.UUID(), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_muted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_wa_id'], ['contacts.wa_id'], ondelete='CASCADE'),
    # fk_chats_last_message_id_messages is added after `messages` exists (below)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_wa_id', name='uq_chats_contact_wa_id')
    )
    op.create_index('ix_chats_pinned_updated', 'chats', ['is_pinned', 'updated_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('wamid', sa.Text(), nullable=True),
    sa.Column('client_msg_id', sa.Text(), nullable=True),
    sa.Column('sender_wa_id', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), server_default=sa.text("'text'"), nullable=False),
    sa.Column('body', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('media_id', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('media_mime', sa.Text(), nullable=True),
    sa.Column('reply_to_wamid', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('in', 'out')", name='ck_messages_direction'),
    sa.CheckConstraint('status BETWEEN 0 AND 4', name='ck_messages_status'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wamid', name='uq_messages_wamid')
    )
    op.create_index('ix_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('uq_messages_chat_client_msg_id', 'messages', ['chat_id', 'client_msg_id'], unique=True, postgresql_where=sa.text('client_msg_id IS NOT NULL'))
    # chats <-> messages reference each other
    op.create_foreign_key('fk_chats_last_message_id_messages', 'chats', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chats_last_message_id_messages', 'chats', type_='foreignkey')
    op.drop_index('uq_messages_chat_client_msg_id', table_name='messages', postgresql_where=sa.text('client_msg_id IS NOT NULL'))
    op.drop_index('ix_messages_chat_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_chats_pinned_updated', table_name='chats')
    op.drop_table('chats')
    op.drop_table('webhook_events')
    op.drop_index('ix_otp_codes_created_at', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('operator')
    op.drop_table('fcm_tokens')
    op.drop_table('contacts')
    op.drop_table('business_number')
    # ### end Alembic commands ###
