"""marketing opt outs

Numbers that pressed STOP under a marketing template (or typed it). The blast
CLI checks this table through /v1/marketing/number/{phone} before sending.

Revision ID: b95854a4e087
Revises: 10f02f7f84b8
Create Date: 2026-10-03 07:53:34.796610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b95854a4e087'
down_revision: Union[str, Sequence[str], None] = '10f02f7f84b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_opt_outs',
    sa.Column('wa_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketing_opt_outs')
    # ### end Alembic commands ###
